# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-16 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sni', '0002_auto_20170416_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addthing',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='newnotice',
            name='sender',
        ),
        migrations.DeleteModel(
            name='addThing',
        ),
        migrations.DeleteModel(
            name='newnotice',
        ),
    ]
